package at.aau.serg.dktserver.communication.enums;

public enum Action {

    ROLL_DICE, BUY_FIELD, BUY_BUILDING, SELL_BUILDING, CREATE_GAME, JOIN_GAME, START_GAME, GAME_CREATED_SUCCESSFULLY, GAME_JOINED_SUCCESSFULLY,
    READY, NOT_READY, CHANGED_READY_STATUS, LEAVE_GAME, HOST_CHANGED, INIT_FIELDS, GAME_DELETED, GAME_STARTED, END_TURN, SUBMIT_CHEAT, MOVE_PLAYER, CONNECTION_LOST,
    RECONNECT_OK, RECONNECT_DISCARD, UPDATE_MONEY,PAY_TAXES, RISIKO_CARD_SHOW, BANK_CARD_SHOW
}

