package at.aau.serg.dktserver.communication.enums;

public enum Action {

    ROLL_DICE, BUY_FIELD, BUY_BUILDING, SELL_BUILDING, CREATE_GAME, JOIN_GAME, START_GAME, GAME_CREATED_SUCCESSFULLY, GAME_JOINED_SUCCESSFULLY,
    READY, NOT_READY, CHANGED_READY_STATUS, LEAVE_GAME, HOST_CHANGED, INIT_FIELDS, GAME_DELETED, GAME_STARTED, MOVE_PLAYER, SUBMIT_CHEAT, END_TURN
}

